version: '3.7'
services:
  api:
    build: 
      context: "."
      dockerfile: ./Dockerfile.api
    image: ${LOGIN_SERVER}/inventory-app/api:v1
    ports:
      - "6000:6000"
    env_file:
      - ./.env
    restart: unless-stopped

  web-app:
    image: ${LOGIN_SERVER}/inventory-app/web-app:v1
    build:
      context: "."
      dockerfile: ./Dockerfile.new-web-app
    restart: unless-stopped
    ports:
      - "80:80"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pauper-Routine-Sneer3-Broiler
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
